.PHONY: clean All

All:
	@echo "----------Building project:[ rrr - Debug ]----------"
	@$(MAKE) -f  "rrr.mk"
clean:
	@echo "----------Cleaning project:[ rrr - Debug ]----------"
	@$(MAKE) -f  "rrr.mk" clean
