import os
Import('*')

lib = env.Clone()
if opt.linux:
    lib.AppendUnique(CPPDEFINES=['NS_ENABLE_SSL', 'NS_ENABLE_DEBUG'])
b = lib.Library('mongoose', ['mongoose.c'])
b = lib.Install(opt.dirLib, [b])
lib.Default(b)

imp = env.Clone()
imp.AppendUnique(CPPPATH=[Dir('.')])
imp.AppendUnique(LIBS=['mongoose'])
if opt.linux:
    imp.AppendUnique(LIBS=['ssl'])

#########################################3

exe = env.Clone()
if opt.linux:
    exe.AppendUnique(CPPDEFINES=['NS_ENABLE_SSL'])
exe.MergeEnv(imp)
src = ['examples/server.c']
a = exe.Program('mongoose', src)
a = exe.Install(opt.dirBin, [a])
exe.Default(a)


#########################################3
Return('imp')
